# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-06 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20181205_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='type',
        ),
    ]
