# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-07 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20181206_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='location',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='1704 rue Crawford, Verdun', max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='brand',
            field=models.CharField(max_length=30),
        ),
    ]
