# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20181206_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numSold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('type', 'seller')]),
        ),
    ]
