# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-20 19:28
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20181209_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='geom',
            field=djgeojson.fields.PointField(null=True),
        ),
    ]
