# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-20 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_seller_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='longitude',
        ),
    ]
