# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20181220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together=set([('brand', 'geom')]),
        ),
    ]
